Table categories {
  category_id int [pk]
  category_name varchar(100) [unique, not null]
  description varchar(255)
}

Table authors {
  author_id int [pk]
  author_name varchar(150) [not null]
  country varchar(100) [not null]
}

Table publishers {
  publisher_id int [pk]
  publisher_name varchar(150) [unique, not null]
  phone varchar(20) [unique, not null]
}

Table books {
  book_id int [pk]
  title varchar(200) [not null]
  isbn varchar(20) [unique, not null]
  author_id int [not null, ref: > authors.author_id]
  publisher_id int [not null, ref: > publishers.publisher_id]
  category_id int [not null, ref: > categories.category_id]
  published_year smallint [not null]
  price decimal(12,2) [not null]
  stock int [not null, default: 0]
  status varchar(10) [not null]
}

Table customers {
  customer_id int [pk]
  full_name varchar(150) [not null]
  email varchar(150) [unique, not null]
  phone varchar(20) [unique, not null]
  membership_level varchar(10) [not null]
  registered_at datetime [not null]
}

Table orders {
  order_id int [pk]
  customer_id int [not null, ref: > customers.customer_id]
  order_date datetime [not null]
  status varchar(20) [not null]
  total_amount decimal(12,2) [not null]
  shipping_fee decimal(12,2) [not null]
}

Table order_items {
  order_item_id int [pk]
  order_id int [not null, ref: > orders.order_id]
  book_id int [not null, ref: > books.book_id]
  quantity int [not null]
  unit_price decimal(12,2) [not null]
}

Table payments {
  payment_id int [pk]
  order_id int [unique, not null, ref: > orders.order_id]
  amount decimal(12,2) [not null]
  payment_method varchar(20) [not null]
  payment_date datetime [not null]
  payment_status varchar(10) [not null]
}
